### ISSUE TITLE
How to configure pkutils as the first dependency

### ISSUE THREAD

**Issue by kenju254** [reubano/pkutils#1]
Machine : OSX El Capitano

When using pkutil how do you ensure that it is the first dependency that is installed. I wasn't able to see that in the Documentation

**Comment by reubano** [comment]
It should work with the following

`setup.py`

``` python
...
setup(
    ...
    setup_requires='pkutils==0.6.1',
    ...
```

Thanks for the reminder. I'll add it to the docs in the next update.
